import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

const root = resolve(process.cwd())
const sourcePath = resolve(root, 'src/config/creditCosts.ts')
const targetPath = resolve(root, 'supabase/functions/_shared/creditCosts.ts')

const source = readFileSync(sourcePath, 'utf-8')

const generatedHeader = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 *
 * Source of truth: src/config/creditCosts.ts
 * Generated by: npm run sync:credit-costs
 */\n\n`

const output = `${generatedHeader}${source}`
writeFileSync(targetPath, output, 'utf-8')

console.log('[sync:credit-costs] Synced: src/config/creditCosts.ts -> supabase/functions/_shared/creditCosts.ts')
